### PR TITLE
types: Fix types for strict setting in tsconfig.

### PR DESCRIPTION
**Pull request by rajzik**
I have added all return types to index.d.ts which caused trouble when lib check and strict are enabled.
Also, I have updated add method which accepts iterable. 

Tested with the latest typescript.

Fix: #173 , #161

### CODE REVIEW

**Comment by bsegault** [comment]
Thank you for this PR, this is exactly what we need.
@ts-thomas Any chance we could have this merged soon?

**Comment by jaymathew** [comment]
Is there something wrong with this merge? If not, can we please merge it?

**Comment by rajzik** [comment]
Can some of the contributors check it?
@ts-thomas?

**Comment by ts-thomas** [comment]
The typescript definition file of the new version >= 0.7.0 need some migration. I've reduced the amount of variations of all parameters in this new version . Hopefully this will simplify the typescript definition file. If you like you can check your changes against the new version and add them as a new PR. Thanks a lot!

**Pull request closed without merging**
