### PR TITLE
Removal of repetition and sorting.

### PR DESCRIPTION
**Pull request by Rzeszow**

### CODE REVIEW

**Comment by ray1981jacob** [comment]
Ok. Ty need your email

**Comment by ts-thomas** [comment]
Thanks a lot 👍

**Comment by ts-thomas** [comment]
> Ok. Ty need your email

You can send me an email to: info@nextapps.de

**Comment by Rzeszow** [comment]
@ts-thomas Thanks! I have to send an email to you?

**Comment by ts-thomas** [comment]
No sorry :)

**Pull request merged**
