### PR TITLE
WIP: Typescript Definitions

### PR DESCRIPTION
**Pull request by RXminuS**
In response to https://github.com/nextapps-de/flexsearch/issues/49 I thought I'd just get something started. As mentioned, I don't think there is any value in doing a typescript rewrite (although Typescript is amazing and we find so many bugs because of strong typing). Instead, I think people are already happy if there is just a good declaration file included.

Would appreciate any help because I'm very short on time @ScreamZ @ts-thomas. Also happy to participate in a bounty if needed.

### CODE REVIEW

**Comment by ScreamZ** [comment]
Hey @RXminuS that's a good idea, I'll try to help on it, I'm starting a project for my company that will probably rely on that search engine.

What kind of bounty you're talking about ?

See ya

**Comment by RXminuS** [comment]
Oh i meant something like https://www.bountysource.com/ . But I think GitHub has it built in now as well.

**Comment by ts-thomas** [comment]
@RXminuS  Nice one thanks. The Typescript declaration interface you made is really helpful.

**Comment by ScreamZ** [comment]
Can we get a release on that ? :) thanks

**Comment by ts-thomas** [comment]
Done:
https://github.com/nextapps-de/flexsearch/releases/tag/0.6.22

**Comment by OneCyrus** [comment]
@ts-thomas: the latest release on npm is 0.6.22 as well but is already 3 months old. and i couldn't find types in there. in which release are the types actually?

**Comment by ts-thomas** [comment]
Sorry I forgot to fetch commits and deploy to NPM. Now it is available in 0.6.23: https://www.npmjs.com/package/flexsearch

**Comment by Hobart2967** [comment]
Heya @ts-thomas , typings are still not available in the latest package, and the package.json is also missing the "typings" attribute

**Comment by ofirpicazo** [comment]
> Heya @ts-thomas , typings are still not available in the latest package, and the package.json is also missing the "typings" attribute

I've sent https://github.com/nextapps-de/flexsearch/pull/258 to add the missing typings.

**Comment by jonhue** [comment]
@ts-thomas, it seems like the type definitions are missing from the latest versions

**Comment by jonhue** [comment]
@ts-thomas it'd be great if we could get a new release!

**Pull request merged**
