### PR TITLE
fix nested export key

### PR DESCRIPTION
**Pull request by tiejunhu**
trying to fix issue #273

### CODE REVIEW

**Comment by ts-thomas** [comment]
Thanks for this PR. I will need some further investigation for this changes if this has no side-effects.

**Review by ryihan — APPROVED** [review]

**Comment by crutchcorn** [comment]
@tiejunhu why was this PR closed? It seems that this fixes a big part of https://github.com/nextapps-de/flexsearch/issues/290

**Comment by tiejunhu** [comment]
> @tiejunhu why was this PR closed? It seems that this fixes a big part of #290

Sorry I thought it's already merged. I'll reopen it.

**Comment by canavci2016** [comment]
i have just seen the function you should do some enhancement on this function. it depends on many paramaters which lead some misunderstandings. i left a link below i hope it might be helpful. i must say that the performance benchmark is amazing.

https://refactoring.guru/smells/long-parameter-list

**Comment by ts-thomas** [comment]
I will merge it and apply some little improvement on top of it.

**Pull request merged**
