### PR TITLE
Don't use an entire array as the key of an object

### PR DESCRIPTION
**Pull request by licarijd**
This solves an issue caused by the following line of code:
```
result[i] = doc_idx[field[i]].search(_query, 0);
```
In this case, field[i] is an array. When field[i] only has one element, the code works as expected since JavaScript will use the value of the one element by default. When field[i] has a length > 1, an error occurs, as an entire list will be used as the key for doc_idx.

This would cause bugs where having more than one field in a list of queries would not work. So, the following would lead to an error:

```
index.search(
        [{ 
          field: ["title", "subtitle"],
          query: "foo",
          bool: "or"
        },{ 
          field: ["title", "subtitle"],
          query: "bar",
          bool: "or"
        },{ 
          field: ["title", "subtitle"],
          query: "test",
          bool: "or"
        }]
      )
```

This issue is fixed by simply iterating through field[i], which is a list.

### CODE REVIEW

**Comment by ts-thomas** [comment]
Nice one. I need to take a look later into this to understand the change and proof it might get conflicts with the upcoming rev3. First look is great.

**Comment by brooke-stephens-cbc** [comment]
Hey Tom, please ignore Justin's PR and take a look at
https://github.com/nextapps-de/flexsearch/pull/143

Thanks

**Comment by ts-thomas** [comment]
Related to this topic: #144

**Comment by licarijd** [comment]
Hi @ts-thomas , I've just put in a one word commit which prevents null objects from being added to search results. This fixes what we were trying to accomplish with https://github.com/nextapps-de/flexsearch/pull/144. You can disregard that PR, and review this one instead.



> Nice one. I need to take a look later into this to understand the change and proof it might get conflicts with the upcoming rev3. First look is great.

**Comment by licarijd** [comment]
Hi @ts-thomas , any updates? My team is hoping to include the library in some upcoming features, and would require this fix

**Comment by ts-thomas** [comment]
This issue is solved in 0.7.0, different queries on the same field could be stacked in one search now. Thanks a lot for your help.

**Pull request closed without merging**
