### PR TITLE
Publish typescript definitions

### PR DESCRIPTION
**Pull request by ehaynes99**
Closes https://github.com/nextapps-de/flexsearch/issues/243

### CODE REVIEW

**Comment by ndrewtl** [comment]
Hi @ts-thomas I saw you commented on #243 asking for a pull request to make this change. This is the PR, could you please review / merge it?

**Comment by ndrewtl** [comment]
Bumping again, @ts-thomas , can you please merge this?

**Comment by amilich** [comment]
Can we merge this?

**Comment by ofirpicazo** [comment]
The existing TypeScript type declarations aren't compatible with v0.7.0, they were made for v0.6.32 so they need to be updated to match the newer API.

**Comment by ehaynes99** [comment]
I'm going to go ahead and close this for now. However, I would vote to keep #243 open as types for this would be quite helpful.

**Comment by Losses** [comment]
> The existing TypeScript type declarations aren't compatible with v0.7.0, they were made for v0.6.32 so they need to be updated to match the newer API.

#266 Provided a updated type definition, anyone can merge it?

**Pull request closed without merging**
