### PR TITLE
Handle chained queries with "or"

### PR DESCRIPTION
**Pull request by brooke-stephens-cbc**
Hi Tom,

This PR is in regards to my colleague Justin's PR.
https://github.com/nextapps-de/flexsearch/pull/142

There we some bugs from his PR that we identified and we believe that this PR fixes those bugs.  We definitely need you to look at it and make sure there are not adverse side effects.

This PR will handle chained queries such as:

index.search(
        [{ 
          field: ["title", "subtitle"],
          query: "foo",
          bool: "or"
        },{ 
          field: ["title", "subtitle"],
          query: "bar",
          bool: "or"
        },{ 
          field: ["title", "subtitle"],
          query: "test",
          bool: "or"
        }]
      )

Please let us know what you think.  Thanks!

### CODE REVIEW

**Comment by ts-thomas** [comment]
Great! I will take a look on it very soon.

**Comment by ts-thomas** [comment]
There is some conflict with the bool logic. Let me explain:

```js
index.search([{
    field: ["title", "subtitle"],
    query: "foo",
    bool: "or"
},{
    field: ["title", "subtitle"],
    query: "bar",
    bool: "or"
},{
    field: ["title", "subtitle"],
    query: "test",
    bool: "or"
}]);
```

It is not clear where the bool parameter should apply:

1. the bool parameter applies to the fields "title" and "subtitle"
2. the bool parameter applies to each query

But probably there is no conflict. Because we could assume that the bool logic between multiple fields are always "or" by default, then the bool from the payload above will apply to each query. This might your desired result and your fix handles this issue perfectly.

To handle both scenarios it needs a complete new style of how bool logic could be applied by the query payload.

Some notes to this PR:
- there are some changes in the package.json which could not be merged
- the vars "has_not" and "has_and" are not applied anymore, which is important for the intersection, therefore these changes will just support "or"
- a query payload needs to have the style from the above example, but there are some more ways supported as a query payload, which will not work anymore
- I would prefer the #142 , is there anything which is not covered there but is included in this PR?
- sadly the continuous integration pipeline is actually broken, but when you run "npm run test" too many tests will not pass anymore

**Comment by ts-thomas** [comment]
Related to this topic: #144

**Comment by brooke-stephens-cbc** [comment]
Thanks for reviewing this PR Tom.  Let me consult with Justin and we will get back to you.  Quick question.  I just want to confirm that query chaining with OR "does not work" in v0.6.32?  Want to make sure it's not just us writing the queries incorrectly.  Thanks!

**Comment by licarijd** [comment]
Hi @ts-thomas , I've made a fix on https://github.com/nextapps-de/flexsearch/pull/142. If you could take a look, it accomplishes what we are trying to do in this PR.

**Pull request closed without merging**
